spring:
  application:
    name: pos-products
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      database: posdb
      authentication-database: admin
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}