server:
  port: 8080
spring:
  application:
    name: pos-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: pos-carts
          uri: lb://pos-carts
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
        - id: pos-products
          uri: lb://pos-products
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: pos-orders
          uri: lb://pos-orders
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}