spring:
  application:
    name: pos-delivery
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      database: posdb
      authentication-database: admin
  cloud:
    function:
      definition: receiveOrder
    stream:
      function:
        bindings:
          receiveOrder-in-0: order-receive
      bindings:
        order-receive:
          destination: order-channel

server:
  port: 8087
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}